=== everyday-solution/ESolutions/ESolutions/Microkernel.Mappings.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:es="http://everydaysolutions.de/schemas/" attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://everydaysolutions.de/schemas/" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="mappings">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="typeGroups">
					<xs:complexType>
						<xs:sequence>
							<xs:element maxOccurs="unbounded" name="typeGroup">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="types">
											<xs:complexType>
												<xs:sequence>
													<xs:element maxOccurs="unbounded" name="type">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="desclaringAssembly">
																	<xs:complexType>
																		<xs:attribute name="name" type="xs:string" use="required" />
																	</xs:complexType>
																</xs:element>
																<xs:element name="implementingType">
																	<xs:complexType>
																		<xs:attribute name="fullName" type="xs:string" use="required" />
																	</xs:complexType>
																</xs:element>
															</xs:sequence>
															<xs:attribute name="interfaceName" type="xs:string" use="required" />
															<xs:attribute name="multiImplementationKey" type="xs:string" use="optional" />
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="name" type="xs:string" use="required" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="assemblies">
					<xs:complexType>
						<xs:sequence>
							<xs:element maxOccurs="unbounded" name="assembly">
								<xs:complexType>
									<xs:attribute name="name" type="xs:string" use="required" />
									<xs:attribute name="pathToFile" type="xs:string" use="required" />
									<xs:attribute name="fileName" type="xs:string" use="required" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="fallbackPath" type="xs:string" use="required" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="targerNamespace" type="xs:string" use="required" />
			<xs:attribute ref="es:schemaLocation" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:attribute name="schemaLocation" type="xs:string" />
</xs:schema>

=== everyday-solution/ESolutions/ESolutions.Test/Microkernel.Mappings.Atomar03.xml
<?xml version="1.0" encoding="utf-8" ?>
<es:mappings
	targerNamespace="http://everydaysolutions.de/schemas/"
   xmlns:es="http://everydaysolutions.de/schemas/"
	es:schemaLocation="es file:///d:/esolutions/esolutions/microkernel.mappings.xsd">
	<es:typeGroups>
		<es:typeGroup name="one">
			<es:types>
				<!-- InitializeWithDuplicateAssemblyMappings -->
				<es:type interfaceName="ESolutions.Test.Interfaces.IDependencyMapping06">
					<es:desclaringAssembly name="ESolutions.Test, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" />
					<es:implementingType fullName="ESolutions.Test.Mocker.DependencyMapping06" />
				</es:type>
			</es:types>
		</es:typeGroup>
	</es:typeGroups>
	<es:assemblies fallbackPath="C:\Code\ESolutions\ESolutions.Test\bin\Debug">
		<es:assembly name="ESolutions.Test, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" pathToFile="C:\Code\ESolutions\ESolutions.Test\bin\Debug" fileName="ESolutions.Test.dll" />
		<es:assembly name="ESolutions.Test, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" pathToFile="C:\Code\ESolutions\ESolutions.Test\bin\Debug" fileName="ESolutions.Test.dll" />
	</es:assemblies>	
</es:mappings>

=== everyday-solution/ESolutions/ESolutions.Test/Microkernel.Mappings.xml
<?xml version="1.0" encoding="utf-8" ?>
<es:mappings
	targerNamespace="http://everydaysolutions.de/schemas/"
   xmlns:es="http://everydaysolutions.de/schemas/"
	es:schemaLocation="es file:///d:/esolutions/esolutions/microkernel.mappings.xsd">
	<es:typeGroups>
		<es:typeGroup name="one">
			<es:types>
				<!-- CreateInstanceWithoutDependencies -->
				<es:type interfaceName="ESolutions.Test.Interfaces.ISimpleMapping">
					<es:desclaringAssembly name="ESolutions.Test, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" />
					<es:implementingType fullName="ESolutions.Test.Mocker.SimpleMapping" />
				</es:type>
				<!-- CreateInstanceWithMappedDependency -->
				<es:type interfaceName="ESolutions.Test.Interfaces.IDependencyMapping01">
					<es:desclaringAssembly name="ESolutions.Test, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" />
					<es:implementingType fullName="ESolutions.Test.Mocker.DependencyMapping01" />
				</es:type>
				<es:type interfaceName="ESolutions.Test.Helper.Contracts.IDependency01">
					<es:desclaringAssembly name="ESolutions.Test.Helper, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" />
					<es:implementingType fullName="ESolutions.Test.Helper.Dependency01" />
				</es:type>
				<!-- CreateInstanceWithIndirectDependencyMapped -->
				<es:type interfaceName="ESolutions.Test.Interfaces.IDependencyMapping02">
					<es:desclaringAssembly name="ESolutions.Test, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" />
					<es:implementingType fullName="ESolutions.Test.Mocker.DependencyMapping02" />
				</es:type>
				<es:type interfaceName="ESolutions.Test.Helper.Contracts.IDependency02">
					<es:desclaringAssembly name="ESolutions.Test.Helper, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" />
					<es:implementingType fullName="ESolutions.Test.Helper.Dependency02" />
				</es:type>
				<!-- CreateInstanceWithoutTypeMapping -->
				<!-- none -->
				<!-- CreateInstanceWithoutAssemblyMapping -->
				<es:type interfaceName="ESolutions.Test.Interfaces.IDependencyMapping04">
					<es:desclaringAssembly name="ESolutions.Test.Unmapped, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" />
					<es:implementingType fullName="ESolutions.Test.Mocker.DependencyMapping04" />
				</es:type>
				<!-- CreateInstanceWithoutAssemblyContainingType -->
				<es:type interfaceName="ESolutions.Test.Interfaces.IDependencyMapping05">
					<es:desclaringAssembly name="ESolutions.Test, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" />
					<es:implementingType fullName="ESolutions.Test.Mocker.DependencyMapping05" />
				</es:type>
				<!-- CreateInstanceNotImplementingInterface -->
				<es:type interfaceName="ESolutions.Test.Interfaces.IDependencyMapping06">
					<es:desclaringAssembly name="ESolutions.Test, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" />
					<es:implementingType fullName="ESolutions.Test.Mocker.DependencyMapping06" />
				</es:type>
				<!-- CreateInstanceWithIndirectDependency -->
				<es:type interfaceName="ESolutions.Test.Interfaces.IDependencyMapping07">
					<es:desclaringAssembly name="ESolutions.Test, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" />
					<es:implementingType fullName="ESolutions.Test.Mocker.DependencyMapping07" />
				</es:type>
			</es:types>
		</es:typeGroup>
	</es:typeGroups>
	<es:assemblies fallbackPath="d:\code\esolutions\out">
		<es:assembly name="ESolutions.Test, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" pathToFile="D:\code\ESolutions\ESolutions.Test\bin\Debug\" fileName="ESolutions.Test.dll" />
		<es:assembly name="ESolutions.Test.Helper, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" pathToFile="D:\code\ESolutions\ESolutions.Test.Helper\bin\Debug" fileName="ESolutions.Test.Helper.dll" />
	</es:assemblies>	
</es:mappings>
